# Configuration for running isodatetime tests on Travis CI
# See https://travis-ci.org/ for more info.

---
dist: xenial
language: python

matrix:
  fast_finish: true
  include:
    - python: 3.5
      env: RUN_COVERAGE=false
    - python: 3.6
      env: RUN_COVERAGE=false
    - python: 3.7
      env: RUN_COVERAGE=true
    - python: 3.7
      env: RUN_COVERAGE=false TZ=UTC
    - python: 3.8-dev
      env: RUN_COVERAGE=false
    - os: osx
      env: RUN_COVERAGE=false
      # Install Python via Homebrew, Travis cannot install Python ATM.
      language: generic
      addons:
        homebrew:
          update: true
          packages: python3
      # Activate a virtualenv (this is how Travis provides a py environment)
      before_install:
        - pip3 install virtualenv
        - virtualenv -p python3 ~/venv
        - source ~/venv/bin/activate

install:
  # Upgrade pip and setuptools as some times the versioning scheme hack fails
  # in Travis-CI.
  - pip install --upgrade pip setuptools
  # Coverage dependencies, coverage for reporting coverage, pytest-cov to
  # enable PyTest to produce coverage reports, and pytest-env to allow
  # PyTest to use environment variables in its configuration (e.g. TZ=UTC).
  - pip install coverage pytest-cov pytest-env pytest-runner
  # Code style dependencies
  - pip install pycodestyle
  - pip install -e .

before_script:
  - pycodestyle -v metomi/isodatetime

script:
  - |
    export COVERAGE_PROCESS_START="${TRAVIS_BUILD_DIR}/.coveragerc"
    export COVERAGE_FILE="${TRAVIS_BUILD_DIR}/.coverage"
    # NOTE: the way to handle long-living commands in the documentation is
    # travis_wait 40 coverage run -m isodatetime.tests.test_time_point
    # but it does not produce any output, which can be frustrating in case of errors.
    # So here we are using the approach documented in the issue
    # https://github.com/travis-ci/travis-ci/issues/4190.
    coverage run setup.py test --pytest-args='--runslow' &
    TEST_PID="$!"
    minutes=0
    limit=50
    while ps -p "${TEST_PID}" >/dev/null 2>&1; do
      echo -n -e " \b" # never leave evidences!
      if ((minutes == limit)); then
        exit 1
      fi
      minutes=$((minutes + 1))
      sleep 60
    done
    wait "${TEST_PID}"

after_success:
  - coverage xml --ignore-errors
  # Report metrics, such as coverage
  - '"${RUN_COVERAGE:-false}" && bash <(curl -s https://codecov.io/bash)'
